version: "3.9"

services:
  alhc-reward:
    build:
      context: ./alhc-reward
      args:
        VITE_API_URL: ${ALHC_VITE_API_URL:-http://localhost:5000}
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always

  web:
    build:
      context: ./web
      args:
        VITE_API_URL: ${WEB_VITE_API_URL:-http://localhost:5000}
    ports:
      - "3001:80"
    depends_on:
      - backend
    restart: always

  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "5000:3000"
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123456}
      POSTGRES_DB: ${POSTGRES_DB:-loyalty}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
